[package]
name = "rustyscript"
description = "Effortless JS Integration for Rust"
license = "MIT OR Apache-2.0"
version = "0.1.3"

keywords = ["rust", "javascript", "deno", "runtime", "embedding"]
categories = ["web-programming", "network-programming", "api-bindings", "compilers", "development-tools::ffi"]

repository = "https://github.com/rscarson/rustyscript"
readme = "readme.md"

edition = "2021"

[features]
default = ["console", "url"]
no_extensions = []
all = ["console", "url", "web"]
url = ["deno_url", "webidl"]
webidl = ["deno_webidl"]
console = ["deno_console"]
web = ["console", "url", "webidl", "deno_web", "deno_crypto", "deno_fetch"]

[dev-dependencies]
version-sync = "0.9.4"
cargo-readme = "3.2.0"

[dependencies]
deno_ast = { version = "0.31.1", features = ["transpiling"]}
deno_core = "0.223.0"
thiserror = "1.0.50"
serde = "1.0.189"
tokio = "1.33.0"

# URL feature
deno_webidl = { version = "0.121.0", optional = true }
deno_url = { version = "0.121.0", optional = true }

# Console feature
deno_console = { version = "0.121.0", optional = true }

# Web feature
deno_fetch = { version = "0.145.0", optional = true }
deno_crypto = { version = "0.135.0", optional = true }
deno_web = { version = "0.152.0", optional = true }

[[example]]
name = "web_features"
required-features = ["web"]