[package]
name = "rustyscript"
description = "Effortless JS Integration for Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.3.0"
repository = "https://github.com/rscarson/rustyscript"

keywords = ["rust", "javascript", "deno", "runtime", "embedding"]
categories = ["web-programming", "network-programming", "api-bindings", "compilers", "development-tools::ffi"]
readme = "readme.md"

[features]
default = ["console", "url", "crypto", "web"]
no_extensions = []
all = ["web"]

webidl = ["deno_webidl"]
url = ["deno_url", "webidl"]
console = ["deno_console"]
crypto = ["deno_crypto", "webidl", "web_stub"]
web_stub = []
web = ["console", "url", "crypto", "deno_web", "deno_fetch", "url_import", "fs_import"]

fs_import = []
url_import = ["reqwest"]

[dev-dependencies]
version-sync = "0.9.4"
criterion = "0.5.1"

[dependencies]
deno_core = "0.238.0"
deno_ast = { version = "0.31.6", features = ["transpiling"]}
thiserror = "1.0.50"
serde = "1.0.194"
tokio = "1.34.0"

# For URL imports
reqwest = { version = "0.11.20", optional = true, features = ["blocking"] }

# Extension features
deno_url = {version = "0.129.0", optional = true}
deno_webidl = {version = "0.129.0", optional = true}
deno_console = {version = "0.129.0", optional = true}
deno_crypto = {version = "0.143.0", optional = true}
deno_fetch = {version = "0.153.0", optional = true}
deno_web = {version = "0.160.0", optional = true}

[[example]]
name = "web_features"
required-features = ["web"]

[[example]]
name = "url_import"
required-features = ["fs_import", "url_import"]

[[bench]]
name = "runtime"
harness = false