[package]
name = "js_playground"
version = "0.5.0"
edition = "2021"

[features]
default = ["console", "url"]
no_extensions = []
all = ["console", "url", "web"]
url = ["deno_url", "webidl"]
webidl = ["deno_webidl"]
console = ["deno_console"]
web = ["console", "url", "webidl", "deno_web", "deno_crypto", "deno_fetch"]

[dev-dependencies]
version-sync = "0.9.4"
cargo-readme = "3.2.0"

[dependencies]
deno_core = "0.221.0"
thiserror = "1.0.40"
serde = "1.0.188"
tokio = "1.32.0"

# Feature deps
deno_fetch = { version = "0.144.0", optional = true }
deno_crypto = { version = "0.134.0", optional = true }
deno_webidl = { version = "0.120.0", optional = true }
deno_url = { version = "0.120.0", optional = true }
deno_console = { version = "0.120.0", optional = true }
deno_web = { version = "0.151.0", optional = true }
