[package]
name = "rustyscript"
description = "Effortless JS Integration for Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.5.0"
repository = "https://github.com/rscarson/rustyscript"

keywords = ["rust", "javascript", "deno", "runtime", "embedding"]
categories = ["web-programming", "network-programming", "api-bindings", "compilers", "development-tools::ffi"]
readme = "readme.md"

[features]
default = ["worker", "console", "url", "crypto"]
no_extensions = []
all = ["web", "io"]

webidl = ["deno_webidl"]
io = ["deno_web", "deno_io", "rustyline", "winapi", "nix", "libc", "once_cell"]
url = ["deno_url", "webidl"]
console = ["deno_console"]
crypto = ["deno_crypto", "webidl", "web_stub"]
web_stub = []
web = ["console", "url", "crypto", "deno_web", "deno_fetch", "url_import", "fs_import", "deno_net"]

# Features for the module loader
fs_import = []
url_import = ["reqwest"]

# Enables the use of the `snapshot` function
snapshot_creation = []

# Enables the threaded worker API
worker = []

[dev-dependencies]
version-sync = "0.9.5"
criterion = "0.5.1"

[dependencies]
deno_core = "0.288.0"
deno_ast = { version = "0.39.2", features = ["transpiling"]}
thiserror = "1.0.61"
serde = "1.0.203"
tokio = "1.38.0"

# For URL imports
reqwest = { version = "0.12.4", optional = true, default-features = false, features = ["blocking", "rustls-tls"] }

# Extension features
deno_url = {version = "0.156.0", optional = true}
deno_webidl = {version = "0.156.0", optional = true}
deno_console = {version = "0.156.0", optional = true}
deno_crypto = {version = "0.170.0", optional = true}
deno_fetch = {version = "0.180.0", optional = true}
deno_web = {version = "0.187.0", optional = true}
deno_net = {version = "0.148.0", optional = true}

# io feature deps
deno_io = {version = "0.66.0", optional = true}
rustyline = {version = "=14.0.0", optional = true}
winapi = {version = "=0.3.9", optional = true}
nix = {version = "=0.28.0", optional = true}
libc = {version = "0.2.155", optional = true}
once_cell = {version = "1.19.0", optional = true}

[[example]]
name = "custom_threaded_worker"
required-features = ["worker"]

[[example]]
name = "default_threaded_worker"
required-features = ["worker"]

[[example]]
name = "url_import"
required-features = ["fs_import", "url_import"]

[[bench]]
name = "runtime"
harness = false
