[workspace]
[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.2.0"
repository = "https://github.com/rscarson/rustyscript"

[package]
name = "rustyscript"
description = "Effortless JS Integration for Rust"
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

keywords = ["rust", "javascript", "deno", "runtime", "embedding"]
categories = ["web-programming", "network-programming", "api-bindings", "compilers", "development-tools::ffi"]
readme = "readme.md"

[features]
default = ["console", "url", "crypto"]
no_extensions = []
all = ["web"]

webidl = ["ext_webidl"]
url = ["ext_url", "webidl"]
console = ["ext_console"]
crypto = ["ext_crypto", "ext_web_stub", "webidl"]
web = ["console", "url", "crypto", "ext_web", "url_import", "fs_import"]

fs_import = []
url_import = ["reqwest"]

[dev-dependencies]
version-sync = "0.9.4"
criterion = "0.5.1"

[workspace.dependencies]
deno_core = "0.224.0"

[dependencies]
deno_core = { workspace = true }
deno_ast = { version = "0.31.3", features = ["transpiling"]}
thiserror = "1.0.50"
serde = "1.0.192"
tokio = "1.34.0"

# For URL imports
reqwest = { version = "0.11.22", optional = true, features = ["blocking"] }

# Extension features
ext_url = { path = "ext/url", optional = true }
ext_webidl = { path = "ext/webidl", optional = true }
ext_console = { path = "ext/console", optional = true }
ext_crypto = { path = "ext/crypto", optional = true }
ext_web_stub = { path = "ext/web_stub", optional = true }
ext_web = { path = "ext/web", optional = true }

[[example]]
name = "web_features"
required-features = ["web"]

[[example]]
name = "url_import"
required-features = ["fs_import", "url_import"]

[[bench]]
name = "runtime"
harness = false